# Generated by Django 5.2.9 on 2025-12-15 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sl_territories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255, unique=True)),
                ('file', models.FileField(upload_to='instructions/')),
                ('parsed_programs', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='instruction_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines', to='sl_territories.instructiontemplate'),
        ),
    ]
