# Generated by Django 5.2.9 on 2026-05-08 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sl_territories', '0003_zone_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='territory',
            name='slot_strategy',
            field=models.CharField(choices=[('auto', 'Max program duration rounded to 30 minutes'), ('fixed_120', 'Fixed average 2-hour slots')], default='auto', max_length=16),
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('booking_start_soon', 'Booking starts soon'), ('wash_timer_started', 'Wash timer started'), ('wash_completed', 'Wash completed'), ('booking_ended', 'Booking ended'), ('machine_unavailable', 'Machine became unavailable')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='sl_territories.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laundry_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'is_read', 'created_at'], name='sl_territor_user_id_53acfc_idx')],
                'unique_together': {('user', 'booking', 'type')},
            },
        ),
    ]
