# Generated by Django 5.2.9 on 2026-05-11 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sl_territories', '0006_booking_wash_confirmation_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('available', 'Available'), ('busy', 'Busy'), ('inactive', 'Inactive'), ('broken', 'Broken')], default='available', max_length=16),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='type',
            field=models.CharField(choices=[('booking_start_soon', 'Booking starts soon'), ('wash_timer_started', 'Wash timer started'), ('wash_completed', 'Wash completed'), ('booking_ended', 'Booking ended'), ('machine_unavailable', 'Machine became unavailable'), ('booking_cancelled', 'Booking cancelled'), ('user_blocked', 'User blocked'), ('reservation_confirmed', 'Reservation confirmed')], max_length=32),
        ),
        migrations.CreateModel(
            name='ReservationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, default='', max_length=16)),
                ('new_status', models.CharField(max_length=16)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='sl_territories.booking')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_status_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TerritoryAdminAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_assignments', to='sl_territories.territory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='territory_admin_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['territory__name', 'user__email'],
                'unique_together': {('user', 'territory')},
            },
        ),
        migrations.CreateModel(
            name='TerritoryUserBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='territory_blocks_created', to=settings.AUTH_USER_MODEL)),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_blocks', to='sl_territories.territory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='territory_blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['territory', 'is_active'], name='sl_territor_territo_57630c_idx'), models.Index(fields=['user', 'is_active'], name='sl_territor_user_id_229018_idx')],
                'unique_together': {('user', 'territory')},
            },
        ),
    ]
