# Generated by Django 5.2.9 on 2026-05-12 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sl_territories', '0008_territoryaccess_noshow_penalty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='type',
            field=models.CharField(choices=[('booking_start_soon', 'Booking starts soon'), ('wash_timer_started', 'Wash timer started'), ('wash_completed', 'Wash completed'), ('booking_ended', 'Booking ended'), ('machine_unavailable', 'Machine became unavailable'), ('booking_cancelled', 'Booking cancelled'), ('user_blocked', 'User blocked'), ('user_unblocked', 'User unblocked'), ('reservation_confirmed', 'Reservation confirmed'), ('territory_deleted', 'Territory deleted')], max_length=32),
        ),
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invite_codes_created', to=settings.AUTH_USER_MODEL)),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_codes', to='sl_territories.territory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProblemReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('machine_broken', 'Machine broken'), ('water_leak', 'Water leak'), ('noise', 'Noise'), ('other', 'Other')], default='other', max_length=32)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('resolved', 'Resolved')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problem_reports', to='sl_territories.machine')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_reports', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problem_reports_resolved', to=settings.AUTH_USER_MODEL)),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_reports', to='sl_territories.territory')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problem_reports', to='sl_territories.zone')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
