# Generated by Django 5.2.9 on 2026-06-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sl_territories', '0011_booking_confirmation_extended'),
    ]

    operations = [
        migrations.AddField(
            model_name='territory',
            name='simple_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='territory',
            name='simple_slot_durations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
