# Generated by Django 5.2.8 on 2025-12-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sl_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartlaundryuser',
            name='public_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='smartlaundryuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('superadmin', 'Super admin')], default='user', max_length=20),
        ),
    ]
